POST http://127.0.0.1:8000/log_in
Content-Type: application/json

{ "username":"Pedro", "password": "Pass1234!" }

###

POST http://127.0.0.1:8000/sign_up
Content-Type: application/json

{ "username":"Pedro", "password": "Pass1234!","email": "juan@gmail.com" }

###
GET  http://127.0.0.1:8000/test_token
Content-Type: application/json
Authorization: Token a3fb959c3840aaea2632611c3c60c5745576a5a3
